/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FileDown } from 'lucide-react';
import { useMission } from '../context/MissionContext';
import { destinations, fuelTypes } from '../rockets';

export default function MissionReport() {
  const { optimization, selectedRocket, missionParams } = useMission();

  if (!optimization || !selectedRocket || !missionParams) return null;

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const destination = destinations.find(d => d.id === missionParams.destination)?.name || 'Unknown';
    const fuelType = fuelTypes.find(f => f.id === missionParams.fuelType)?.name || 'Unknown';

    // Header
    doc.setFontSize(22);
    doc.setTextColor(2, 132, 199); // sky-600
    doc.text('OPTANIUM MISSION REPORT', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-400
    doc.text(`Generated on ${new Date().toLocaleString()}`, pageWidth / 2, 28, { align: 'center' });

    // Mission Overview
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text('Mission Overview', 14, 40);
    
    autoTable(doc, {
      startY: 45,
      head: [['Parameter', 'Detail']],
      body: [
        ['Vessel', selectedRocket.name],
        ['Destination', destination],
        ['Fuel Type', fuelType],
        ['Mission Duration', `${missionParams.duration} Days`],
        ['Payload Weight', `${missionParams.payloadWeight} Metric Tons`],
        ['Readiness Status', optimization.successRate >= 0.9 ? 'READY' : (optimization.successRate >= 0.7 ? 'NEEDS TESTING' : 'UNSAFE')],
        ['Success Probability', `${(optimization.successRate * 100).toFixed(2)}%`],
      ],
      theme: 'striped',
      headStyles: { fillColor: [2, 132, 199] },
    });

    // Performance Metrics
    const finalY = (doc as any).lastAutoTable.finalY || 100;
    doc.setFontSize(14);
    doc.text('Performance Optimization Metrics', 14, finalY + 15);

    autoTable(doc, {
      startY: finalY + 20,
      head: [['Metric', 'Original', 'Optimized', 'Delta']],
      body: [
        ['Fuel Usage', `${optimization.original.fuelUsage}T`, `${optimization.optimized.fuelUsage}T`, `-${optimization.savings.fuel}%`],
        ['Duration', `${optimization.original.duration} Days`, `${optimization.optimized.duration} Days`, `-${optimization.savings.time}%`],
        ['Efficiency Score', `${optimization.original.efficiency}`, `${optimization.optimized.efficiency}`, `+${((optimization.optimized.efficiency - optimization.original.efficiency) / optimization.original.efficiency * 100).toFixed(1)}%`],
        ['Total Thrust', `${optimization.original.thrust} kN`, `${optimization.optimized.thrust} kN`, `+${((optimization.optimized.thrust - optimization.original.thrust) / optimization.original.thrust * 100).toFixed(1)}%`],
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42] },
    });

    // Strategy details
    const stratY = (doc as any).lastAutoTable.finalY || 180;
    doc.setFontSize(14);
    doc.text('Optimization Strategies', 14, stratY + 15);
    
    doc.setFontSize(10);
    let offset = stratY + 22;
    
    const addSection = (title: string, items: string[]) => {
      doc.setFont('Helvetica', 'bold');
      doc.text(title, 14, offset);
      doc.setFont('Helvetica', 'normal');
      offset += 5;
      items.forEach(item => {
        const lines = doc.splitTextToSize(`• ${item}`, pageWidth - 28);
        doc.text(lines, 14, offset);
        offset += (lines.length * 5);
      });
      offset += 3;
    };

    addSection('Engine & Materials', [...optimization.engineUpdates, ...optimization.materialImprovements]);
    
    if (offset > 270) {
      doc.addPage();
      offset = 20;
    }
    
    addSection('Structural & Layout', [...optimization.structuralModifications, optimization.payloadBalancing]);
    addSection('Trajectory & Fuel', [optimization.trajectoryOptimization, optimization.fuelOptimization]);

    // Risk Assessment
    if (offset > 240) {
      doc.addPage();
      offset = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont('Helvetica', 'bold');
    doc.text('Risk Vector Assessment', 14, offset + 10);
    
    autoTable(doc, {
      startY: offset + 15,
      head: [['Risk Factor', 'Probability']],
      body: optimization.riskFactors.map(rf => [rf.factor, `${(rf.probability * 100).toFixed(2)}%`]),
      theme: 'striped',
      headStyles: { fillColor: [220, 38, 38] }, // red-600
    });

    // Footer on last page
    const lastY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text('Generated by Optanium Mission Optimization Intelligence v2.4.1', pageWidth / 2, 285, { align: 'center' });

    doc.save(`Optanium_Mission_Report_${selectedRocket.name.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <button 
      onClick={downloadPDF}
      className="flex items-center gap-3 px-10 py-4 bg-white border-2 border-sky-600 text-sky-600 font-black text-xs rounded hover:bg-sky-50 transition-all uppercase tracking-[0.2em] group shadow-sm"
    >
      <FileDown size={18} className="group-hover:-translate-y-0.5 transition-transform" />
      Download PDF Report
    </button>
  );
}
